### ISSUE TITLE
some error has disppear when run tb/make

### ISSUE THREAD

**Issue by langrange-L** [ultraembedded/core_sdram_axi4#1]
testbench.h: In constructor ‘testbench::testbench(sc_core::sc_module_name)’:
testbench_vbase.h:12:41: error: invalid new-expression of abstract class type ‘VerilatedVcdSc’
             VerilatedVcdSc *v_vcd = new VerilatedVcdSc; \
                                         ^
testbench.h:84:9: note: in expansion of macro ‘verilator_trace_enable’
         verilator_trace_enable("verilator.vcd", m_dut);
         ^
In file included from testbench_vbase.h:6:0,
                 from testbench.h:2,
                 from main.cpp:2:
/usr/share/verilator/include/verilated_vcd_sc.h:36:7: note:   because the following virtual functions are pure within ‘VerilatedVcdSc’: class VerilatedVcdSc

**Comment by ultraembedded** [comment]
This issue is caused by an issue with certain versions of SYS-C + Verilator.

See the fix here;
https://www.veripool.org/issues/1251-Verilator-Compilation-error-for-SystemC-2-3-2
