### ISSUE TITLE
port mapping the top module with AXI ip

### ISSUE THREAD

**Issue by Madesh12** [ultraembedded/core_sdram_axi4#2]
We are using sdram in our FPGA board. Our SDRAM same that you have given project.
So I am working with your code. I want to create axi ip from your code and use it with the microblaze. I cannot port map Some signals in the top module with AXI4 peripheral in the creation of AXI ip. I gave the picture that I have stucked.

**Comment by ultraembedded** [comment]
It looks like you are connecting an AXI4-Lite interface to a full AXI-4 target, so you need to tie off the following inputs;

AWID = 0 // X
AWBURST= 1 // INCR
AWLEN = 0 // SINGLE
WLAST = 1  // SINGLE
ARID = 0 // X
ARBURST = 1 // INCR
ARLEN = 0 // SINGLE

**Comment by Madesh12** [comment]
I have created the IP using your code. I just created the simple microblaze
design with SDRAM. while running the design I regularly getting multiple
driver nets error(screenshots added here). Please share your knowledge

**Comment by Madesh12** [comment]
This is my microblaze design with SDRAM

**Comment by ultraembedded** [comment]
I don’t see any screenshot.

**Comment by Madesh12** [comment]
these are all the screenshots

**Comment by ultraembedded** [comment]
They are not showing up.

**Comment by Madesh12** [comment]
please visit link to see the images
https://ibb.co/GpyjjB4
https://ibb.co/djKTd4n
